language: php

php:
    - 5.6
    - 5.5
    - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install: composer update --prefer-dist --no-interaction

script:
  - phpunit --coverage-text
